baseurl = "https://b-hemanth.com/"
languageCode = "en-us"
title = "Hemanth Bharatha Chakravarthy"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/b-hemanth"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/hemanthbc/"

[params]
    description = "Hemanth Bharatha Chakravarthy"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "hbc_logo.png"
    width = 50
    height = 50
    alt = "Logo"

